{{- $minio := .Values.minioHub | default dict -}}
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: minio-hub
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: minio-hub
  host: {{ $minio.host | default "gitlab-minio-svc.gitlab-system.svc.cluster.local" | quote }}
  port: {{ $minio.port | default 9000 }}
