apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: kafka-east-tst
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: kafka-east-tst
  host: kafka-east-tst
  port: 9092
