apiVersion: v2
name: ia-computer-vision
description: Multi-cluster AI Computer Vision Validated Pattern
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: clustergroup
    version: 0.9.*
    repository: https://charts.validatedpatterns.io
icon: https://maximilianopizarro.github.io/ia-computer-vision/images/ia-computer-vision/ia-computer-vision-logo.png
maintainers:
  - name: Maximiliano Pizarro
    email: mapizarr@redhat.com
