apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: ${{ values.name }}-oidc
  namespace: ${{ values.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ${{ values.name }}
  rules:
    authentication:
      oidc:
        issuerUrl: https://rhbk-${{ values.name }}.${{ values.spokeClusterDomain }}/realms/neuroface
        scopes:
          - openid
          - profile
          - email
