apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neuroface-ai-gateway-key
  namespace: ${{ values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: neuroface-ai-gateway-key
    creationPolicy: Owner
  data:
    - secretKey: platformApiKey
      remoteRef:
        key: secret/data/hub/ai-gateway-platform-keys
        property: platformApiKey
