apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
spec:
  parentRefs:
    - name: neuroface-spoke-gateway
      namespace: neuroface
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /user/${{ values.owner }}/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: neuroface-frontend
          port: 8080
