{{- if .Values.industrialEdge.enabled }}
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: ie-api-{{ include "spoke-interconnect.clusterName" . }}
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: ie-api-{{ include "spoke-interconnect.clusterName" . }}
  host: line-dashboard.industrial-edge-tst-all.svc.cluster.local
  port: 3000
{{- end }}
