apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: otel-hub
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: otel-hub
  host: otel-hub
  port: 4317
