{{- if .Values.industrialEdge.enabled }}
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: kafka-{{ include "spoke-interconnect.clusterName" . }}-datalake
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: kafka-{{ include "spoke-interconnect.clusterName" . }}-datalake
  host: prod-cluster-kafka-bootstrap.industrial-edge-data-lake.svc.cluster.local
  port: 9092
{{- end }}
