apiVersion: v1
kind: Secret
metadata:
  name: prometheus-auth-proxy-token
  namespace: service-interconnect
  annotations:
    kubernetes.io/service-account.name: prometheus-auth-proxy
    argocd.argoproj.io/sync-wave: "2"
type: kubernetes.io/service-account-token
