apiVersion: v1
kind: Service
metadata:
  name: prometheus-auth-proxy
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: prometheus-auth-proxy
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
