apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: neuroface-app-{{ include "spoke-neuroface.clusterName" . }}
  namespace: service-interconnect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  routingKey: neuroface-app-{{ include "spoke-neuroface.clusterName" . }}
  host: neuroface-spoke-gateway-istio.neuroface.svc.cluster.local
  port: 8080
