site_name: AI Computer Vision Workshop
site_description: Onboarding for AI Computer Vision at the Edge workshop users
nav:
  - Home: index.md
  - Login: login.md
  - AI CV software template: ai-computer-vision-scaffolding.md
  - Vault and ESO secrets: vault-eso-secrets.md
  - Create a component (Industrial Edge): create-component.md
  - Pipelines and Quay: pipelines.md
  - Observability: observability.md
  - Kuadrant API keys: kuadrant-apis.md
plugins:
  - techdocs-core
