{{- $hub := include "developer-hub.clusterDomain" . }}
{{- $catalog := .Files.Get "files/catalog/neuroface-system.yaml" | replace "__HUB_APPS_DOMAIN__" $hub -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-hub-catalog-neuroface
  namespace: developer-hub
  labels:
    rhdh.redhat.com/ext-config-sync: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  neuroface-system.yaml: |
{{ $catalog | nindent 4 }}
