apiVersion: v1
kind: Secret
metadata:
  name: grafana-thanos-reader-token
  namespace: openshift-cluster-observability-operator
  annotations:
    kubernetes.io/service-account.name: grafana-thanos-reader
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/service-account-token
