{{- if eq (.Values.clusterRole | default "hub") "hub" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-thanos-reader
  namespace: openshift-cluster-observability-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
