apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  namespace: istio-system
  profile: ambient
  values:
    pilot:
      env:
        PILOT_ENABLE_AMBIENT: "true"
      trustedZtunnelNamespace: ztunnel
    global:
      platform: openshift
      {{- if .Values.clusterName }}
      multiCluster:
        clusterName: {{ .Values.clusterName }}
      {{- end }}
    meshConfig:
      extensionProviders:
        - name: otel-tracing
          opentelemetry:
            service: cluster-collector-collector.openshift-opentelemetry.svc.cluster.local
            port: 4317
---
apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
  namespace: istio-cni
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  namespace: istio-cni
  profile: ambient
  values:
    cni:
      ambient:
        reconcileIptablesOnStartup: true
---
apiVersion: sailoperator.io/v1
kind: ZTunnel
metadata:
  name: default
  namespace: ztunnel
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  namespace: ztunnel
  {{- if .Values.clusterName }}
  values:
    ztunnel:
      multiCluster:
        clusterName: {{ .Values.clusterName }}
  {{- end }}
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  metrics:
    - providers:
        - name: prometheus
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
{{- $ambientNamespaces := list "neuroface" "neuroface-cv" }}
{{- if eq .Values.clusterRole "hub" }}
{{- $ambientNamespaces = append $ambientNamespaces "neuroface-gateway-system" "devspaces" "developer-hub" }}
{{- end }}
{{- range $ambientNamespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: ServerSideApply=true
{{- end }}
