apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: hub-spoke-gitops
  namespace: {{ .Values.gitOpsCluster.namespace | default "openshift-gitops" }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: {{ .Values.gitOpsCluster.argoNamespace | default "vp-gitops" }}
  placementRef:
    kind: Placement
    name: {{ .Values.gitOpsCluster.placementName | default "hub-spoke-placement" }}
    apiVersion: cluster.open-cluster-management.io/v1beta1
