{{- $gitopsNs := .Values.global.gitOpsSubNamespace | default "openshift-gitops-operator" -}}
{{- if ne $gitopsNs "openshift-operators" }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: spoke-gitops-og-cleanup
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "3"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: spoke-gitops-og-cleanup
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            include:
              - {{ $gitopsNs }}
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: {{ $gitopsNs }}
                  namespace: {{ $gitopsNs }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: spoke-gitops-og-cleanup-binding
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
placementRef:
  name: spoke-gitops-og-cleanup-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: spoke-gitops-og-cleanup
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: spoke-gitops-og-cleanup-placement
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: NotIn
              values:
                - "true"
            - key: clusterGroup
              operator: In
              values:
                - east
                - west
{{- end }}
