{{- if and .Values.spokeCredentials.enabled (eq (include "acm-hub-spoke.spokeCredMode" .) "inline") }}
{{- $sc := .Values.spokeCredentials -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sc.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  {{- range $name, $cluster := $sc.clusters }}
  {{- if and $cluster.token $cluster.apiUrl }}
  {{ $name }}-token: {{ $cluster.token | quote }}
  {{ $name }}-api-url: {{ $cluster.apiUrl | quote }}
  {{- end }}
  {{- end }}
{{- end }}
