{{- if .Values.kuadrant.enabled | default false }}
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: redhat-connectivity-link-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  observability:
    enable: true
  mtls:
    enable: true
    authorino: true
    limitador: true
---
apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: redhat-connectivity-link-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
---
apiVersion: limitador.kuadrant.io/v1alpha1
kind: Limitador
metadata:
  name: limitador
  namespace: redhat-connectivity-link-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  limits: []
{{- end }}
