apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: neuroface-gateway
  namespace: neuroface-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    haproxy.router.openshift.io/timeout: 3600s
    haproxy.router.openshift.io/hsts_header: max-age=0
spec:
  host: neuroface.{{ include "neuroface-gateway.clusterDomain" . }}
  port:
    targetPort: http
  to:
    kind: Service
    name: neuroface-gateway-istio
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: neuroface-cv
  namespace: neuroface-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    haproxy.router.openshift.io/timeout: 3600s
    haproxy.router.openshift.io/hsts_header: max-age=0
spec:
  host: neuroface-cv.{{ include "neuroface-gateway.clusterDomain" . }}
  port:
    targetPort: http
  to:
    kind: Service
    name: neuroface-gateway-istio
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
