apiVersion: v1
kind: Namespace
metadata:
  name: neuroface-cv
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: ServerSideApply=true
