baseURL: https://maximilianopizarro.github.io/ia-computer-vision/
languageCode: en-us
title: AI Computer Vision

security:
  exec:
    allow:
      - '^asciidoctor$'
      - '^dart-sass-embedded$'
      - '^go$'
      - '^npx$'
      - '^postcss$'
      - '^tailwindcss$'

module:
  imports:
    - path: github.com/alex-shpak/hugo-book

params:
  author: Maximiliano Pizarro
  description: Multi-cluster AI Computer Vision at the Edge Validated Pattern
  BookToC: true
  BookSection: patterns

markup:
  asciidocExt:
    attributes:
      source-highlighter: rouge
      icons: font
      sectanchors: ""
      sectlinks: ""
      experimental: ""
    safeMode: unsafe

menu:
  main:
    - name: Home
      url: /patterns/ia-computer-vision/
      weight: 10
    - name: Getting started
      url: /patterns/ia-computer-vision/getting-started/
      weight: 20
    - name: Architecture
      url: /patterns/ia-computer-vision/architecture/
      weight: 30
    - name: Troubleshooting
      url: /patterns/ia-computer-vision/troubleshooting/
      weight: 40
