apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitlab-operator-group
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - {{ .Values.namespace }}
{{- if .Values.runnerEnabled }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitlab-runner-operator-group
  namespace: {{ .Values.runnerNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - {{ .Values.runnerNamespace }}
{{- end }}
