{{- if .Values.runnerEnabled }}
{{- $webUrl := include "gitlab-operator.webUrl" . -}}
apiVersion: apps.gitlab.com/v1beta2
kind: Runner
metadata:
  name: gitlab-runner
  namespace: {{ .Values.runnerNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  gitlabUrl: {{ $webUrl | quote }}
  token: gitlab-runner-token
  tags: openshift,kubernetes,workshop
  buildImage: registry.access.redhat.com/ubi9/ubi-minimal:latest
{{- end }}
