apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-operator-kubernetes
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.operator.channel }}
  name: {{ .Values.operator.packageName }}
  source: {{ .Values.operator.source }}
  sourceNamespace: openshift-marketplace
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
{{- with .Values.operator.controllerResources }}
  config:
    resources:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- if .Values.runnerEnabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-runner-operator
  namespace: {{ .Values.runnerNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.runnerOperator.channel }}
  name: {{ .Values.runnerOperator.packageName }}
  source: {{ .Values.runnerOperator.source }}
  sourceNamespace: openshift-marketplace
  installPlanApproval: {{ .Values.runnerOperator.installPlanApproval }}
{{- end }}
